name: power_widget
description: A widget which can move by gesture
version: 0.0.44
author: "baobmb <s8871404@gmail.com>"
homepage: "https://github.com/Baobomb/MovableWidget/tree/master/movable_widget"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
#  plugin:
#    platforms:
#      android:
#        package: com.bao.movable_widget
#        pluginClass: MovableWidget
#      ios:
#        package: com.bao.movable_widget
#        pluginClass: MovableWidget
