name: movable_widget
description: A widget which can move by gesture
version: 0.0.1
author: "Bao Chen"
homepage: ""

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.bao.movable_widget
        pluginClass: MovableWidget
      ios:
        package: com.bao.movable_widget
        pluginClass: MovableWidget
